### ISSUE TITLE
Typo on title

### ISSUE THREAD

**Issue by BarnabeD** [fractaledmind/fractaledmind.github.io#1]
Hello Stephen, 
I’m on my phone so, I can’t really fix by myself…

There is a typo « deplay » instead of « deploy ». 

https://github.com/fractaledmind/fractaledmind.github.io/blob/4a143d8953ce627621cdf6b167e2941a3222ca95/src/_posts/2023-12-28-how-to-deloy-a-hatchbox-app.md?plain=1#L2

Thanks for this post and all others !

**Comment by fractaledmind** [comment]
Fixed. Thank you.
